pub fn qualified<'a>(namespace: &str, name: &'a str) -> &'a str {
    match (namespace, name) {
        ("process", "parentPid") => "parent",
        ("process", "cpuMillis") => "cpu",
        ("process", "peakResidentMemoryBytes") => "memory",
        ("process", "terminationRequested") => "stopping",
        ("sqlite", "execute") => "run",
        ("net", "tcpConnect") => "connect",
        ("net", "tcpListen") => "listen",
        ("net", "tcpAccept") => "accept",
        ("net", "tcpAcceptMany") => "acceptMany",
        ("net", "udpConnect") => "udp",
        ("net", "udpBind") => "bind",
        ("net", "localPort") => "port",
        ("net", "peerAddress") => "peer",
        ("net", "localAddress") => "local",
        ("net", "sendText") => "write",
        ("net", "sendTextWithTimeout") => "writeTimeout",
        ("net", "sendTextProgress") => "writeFrom",
        ("net", "sendTextParts") => "writeParts",
        ("net", "sendTextTo") => "writeTo",
        ("net", "sendTextToParts") => "writePartsTo",
        ("net", "receiveText") => "read",
        ("net", "receiveTextMany") => "readMany",
        ("net", "receiveTextFrom") => "readFrom",
        ("net", "receiveTextFromMany") => "readManyFrom",
        ("net", "setNonblocking") => "nonblocking",
        ("net", "setNoDelay") => "noDelay",
        ("net", "setKeepAlive") => "keepAlive",
        ("net", "waitReadable") => "readable",
        ("net", "waitWritable") => "writable",
        ("net", "waitReadableMany") => "readableMany",
        ("net", "waitWritableMany") => "writableMany",
        ("net", "waitReadyMany") => "readyMany",
        ("net", "shutdownRead") => "closeRead",
        ("net", "shutdownWrite") => "closeWrite",
        ("http", "receiveRequestHead") => "readRequest",
        ("http", "receiveRequestHeadWithHeaders") => "readRequestHeaders",
        ("http", "receiveRequestWithTextBody") => "readRequestBody",
        ("http", "receiveResponseHeadWithHeaders") => "readResponse",
        ("http", "receiveResponseWithTextBody") => "readResponseBody",
        ("http", "sendTextRequest") => "request",
        ("http", "requestWithHeaders") | ("http", "sendTextRequestWithHeaders") => "requestHeaders",
        ("http", "sendTextResponse") => "respond",
        ("http", "respondWithHeaders") | ("http", "sendTextResponseWithHeaders") => {
            "respondHeaders"
        }
        ("url", "parseHttp") => "parse",
        ("url", "parseFormQuery") => "query",
        ("url", "decodeComponent") => "decode",
        ("url", "encodeComponent") => "encode",
        ("url", "decodeFormComponent") => "decodeForm",
        ("url", "encodeFormComponent") => "encodeForm",
        ("locale", "formatNumber") => "number",
        ("locale", "formatDateTime") => "date",
        ("locale", "formatCurrency") => "currency",
        ("worker", "joinChildren") => "joinAll",
        ("worker", "cancelChildren") => "cancelAll",
        ("channel", "create") => "open",
        ("channel", "send") => "write",
        ("channel", "receive") => "read",
        ("time", "unixMillis") => "now",
        ("time", "monotonicMillis") => "monotonic",
        ("time", "sleepMillis") => "sleep",
        ("time", "sleepUntilMonotonic") => "sleepUntil",
        ("time", "utcUnixMillis") => "utc",
        ("time", "utcYear") => "year",
        ("time", "utcMonth") => "month",
        ("time", "utcDay") => "day",
        ("time", "utcHour") => "hour",
        ("time", "utcMinute") => "minute",
        ("time", "utcSecond") => "second",
        ("time", "utcMillisecond") => "millis",
        ("time", "utcWeekday") => "weekday",
        ("time", "utcDayOfYear") => "dayOfYear",
        ("file", "modifiedUnixMillis") => "modified",
        ("directory", "modifiedUnixMillis") => "modified",
        ("frame", "request") => "next",
        ("clipboard", "setText") => "write",
        ("clipboard", "readText") => "read",
        ("fileDialog", "openFile") => "open",
        ("fileDialog", "saveFile") => "save",
        ("fileDialog", "selectDirectory") => "folder",
        ("focus", "previous") => "prior",
        ("focus", "previousIn") => "priorIn",
        ("textInput", "selectionStart") => "start",
        ("textInput", "selectionEnd") => "end",
        ("textInput", "setCaret") => "caret",
        ("textInput", "setSelection") => "select",
        ("android", "sdkInt") => "sdk",
        ("android", "hasSystemFeature") => "feature",
        ("android", "keepScreenOn") => "awake",
        ("android", "finishActivity") => "finish",
        ("android", "scheduleBackgroundJob") => "schedule",
        ("android", "cancelBackgroundJob") => "cancelJob",
        ("android", "openUrl") => "open",
        ("android", "openAppSettings") => "settings",
        ("android", "openNotificationSettings") => "noticeSettings",
        ("android", "setClipboardText") => "clipboard",
        ("android", "focusNext") => "next",
        ("android", "focusPrevious") => "prior",
        ("android", "focusFirst") => "first",
        ("android", "focusLast") => "last",
        ("android", "clearFocus") => "blur",
        ("android", "selectionStart") => "start",
        ("android", "selectionEnd") => "end",
        ("android", "setCaret") => "caret",
        ("android", "setSelection") => "select",
        ("android", "setImeAction") => "ime",
        ("android", "pickFile") => "file",
        ("android", "pickMedia") => "media",
        ("android", "pickDirectory") => "folder",
        ("android", "createNotificationChannel") => "channel",
        ("android", "permissionGranted") => "allowed",
        ("android", "requestPermission") => "ask",
        ("android", "notificationPermissionGranted") => "noticeAllowed",
        ("android", "requestNotificationPermission") => "askNotice",
        ("android", "notifyUrlAction") => "notifyUrl",
        ("android", "cancelNotification") => "cancelNotice",
        ("android", "startMicrophoneRecording") => "record",
        ("android", "stopMicrophoneRecording") => "stopRecord",
        ("android", "secureStore") => "store",
        ("android", "secureRead") => "load",
        ("android", "secureRemove") => "erase",
        _ => name,
    }
}

pub fn qualified_impl<'a>(namespace: &str, name: &'a str) -> &'a str {
    match (namespace, name) {
        ("process", "parent") => "parentPid",
        ("process", "cpu") => "cpuMillis",
        ("process", "memory") => "peakResidentMemoryBytes",
        ("process", "stopping") => "terminationRequested",
        ("sqlite", "run") => "execute",
        ("net", "udp") => "udpConnect",
        ("net", "bind") => "udpBind",
        ("net", "port") => "localPort",
        ("net", "peer") => "peerAddress",
        ("net", "local") => "localAddress",
        ("net", "write") => "sendText",
        ("net", "writeTimeout") => "sendTextWithTimeout",
        ("net", "writeFrom") => "sendTextProgress",
        ("net", "writeParts") => "sendTextParts",
        ("net", "writeTo") => "sendTextTo",
        ("net", "writePartsTo") => "sendTextToParts",
        ("net", "read") => "receiveText",
        ("net", "readMany") => "receiveTextMany",
        ("net", "readFrom") => "receiveTextFrom",
        ("net", "readManyFrom") => "receiveTextFromMany",
        ("net", "nonblocking") => "setNonblocking",
        ("net", "noDelay") => "setNoDelay",
        ("net", "keepAlive") => "setKeepAlive",
        ("net", "readable") => "waitReadable",
        ("net", "writable") => "waitWritable",
        ("net", "readableMany") => "waitReadableMany",
        ("net", "writableMany") => "waitWritableMany",
        ("net", "readyMany") => "waitReadyMany",
        ("net", "closeRead") => "shutdownRead",
        ("net", "closeWrite") => "shutdownWrite",
        ("http", "readRequest") => "receiveRequestHead",
        ("http", "readRequestHeaders") => "receiveRequestHeadWithHeaders",
        ("http", "readRequestBody") => "receiveRequestWithTextBody",
        ("http", "readResponse") => "receiveResponseHeadWithHeaders",
        ("http", "readResponseBody") => "receiveResponseWithTextBody",
        ("http", "requestHeaders") => "requestWithHeaders",
        ("http", "respondHeaders") => "respondWithHeaders",
        ("url", "parse") => "parseHttp",
        ("url", "query") => "parseFormQuery",
        ("url", "decode") => "decodeComponent",
        ("url", "encode") => "encodeComponent",
        ("url", "decodeForm") => "decodeFormComponent",
        ("url", "encodeForm") => "encodeFormComponent",
        ("locale", "number") => "formatNumber",
        ("locale", "date") => "formatDateTime",
        ("locale", "currency") => "formatCurrency",
        ("worker", "joinAll") => "joinChildren",
        ("worker", "cancelAll") => "cancelChildren",
        ("channel", "open") => "create",
        ("channel", "write") => "send",
        ("channel", "read") => "receive",
        ("time", "now") => "unixMillis",
        ("time", "monotonic") => "monotonicMillis",
        ("time", "sleepUntil") => "sleepUntilMonotonic",
        ("time", "utc") => "utcUnixMillis",
        ("time", "year") => "utcYear",
        ("time", "month") => "utcMonth",
        ("time", "day") => "utcDay",
        ("time", "hour") => "utcHour",
        ("time", "minute") => "utcMinute",
        ("time", "second") => "utcSecond",
        ("time", "millis") => "utcMillisecond",
        ("time", "weekday") => "utcWeekday",
        ("time", "dayOfYear") => "utcDayOfYear",
        ("file", "modified") => "modifiedUnixMillis",
        ("directory", "modified") => "modifiedUnixMillis",
        ("frame", "next") => "request",
        ("fileDialog", "folder") => "selectDirectory",
        ("focus", "prior") => "previous",
        ("focus", "priorIn") => "previousIn",
        ("textInput", "start") => "selectionStart",
        ("textInput", "end") => "selectionEnd",
        ("textInput", "caret") => "setCaret",
        ("textInput", "select") => "setSelection",
        ("android", "sdk") => "sdkInt",
        ("android", "feature") => "hasSystemFeature",
        ("android", "awake") => "keepScreenOn",
        ("android", "finish") => "finishActivity",
        ("android", "schedule") => "scheduleBackgroundJob",
        ("android", "cancelJob") => "cancelBackgroundJob",
        ("android", "open") => "openUrl",
        ("android", "settings") => "openAppSettings",
        ("android", "noticeSettings") => "openNotificationSettings",
        ("android", "clipboard") => "setClipboardText",
        ("android", "next") => "focusNext",
        ("android", "prior") => "focusPrevious",
        ("android", "first") => "focusFirst",
        ("android", "last") => "focusLast",
        ("android", "blur") => "clearFocus",
        ("android", "start") => "selectionStart",
        ("android", "end") => "selectionEnd",
        ("android", "caret") => "setCaret",
        ("android", "select") => "setSelection",
        ("android", "ime") => "setImeAction",
        ("android", "file") => "pickFile",
        ("android", "media") => "pickMedia",
        ("android", "folder") => "pickDirectory",
        ("android", "channel") => "createNotificationChannel",
        ("android", "allowed") => "permissionGranted",
        ("android", "ask") => "requestPermission",
        ("android", "noticeAllowed") => "notificationPermissionGranted",
        ("android", "askNotice") => "requestNotificationPermission",
        ("android", "notifyUrl") => "notifyUrlAction",
        ("android", "cancelNotice") => "cancelNotification",
        ("android", "record") => "startMicrophoneRecording",
        ("android", "stopRecord") => "stopMicrophoneRecording",
        ("android", "store") => "secureStore",
        ("android", "load") => "secureRead",
        ("android", "erase") => "secureRemove",
        _ => name,
    }
}

pub fn global<'a>(name: &'a str) -> &'a str {
    match name {
        "filter" => "where",
        "every" => "all",
        "concat" => "merge",
        "distinct" => "unique",
        "flatten" => "flat",
        "sorted" => "sort",
        "chunked" => "chunk",
        _ => name,
    }
}

pub fn global_impl<'a>(name: &'a str) -> &'a str {
    match name {
        "all" => "every",
        "merge" => "concat",
        "unique" => "distinct",
        "flat" => "flatten",
        "sort" => "sorted",
        "chunk" => "chunked",
        _ => name,
    }
}

pub fn list_member<'a>(name: &'a str) -> &'a str {
    match name {
        "length" => "count",
        "isEmpty" => "empty",
        "isNotEmpty" => "nonempty",
        "single" => "only",
        _ => name,
    }
}

pub fn list_member_impl<'a>(name: &'a str) -> &'a str {
    match name {
        "count" => "length",
        "empty" => "isEmpty",
        "nonempty" => "isNotEmpty",
        "only" => "single",
        _ => name,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn canonical_names_are_short_and_legacy_names_remain_resolvable() {
        assert_eq!(qualified("android", "startMicrophoneRecording"), "record");
        assert_eq!(qualified("android", "secureRead"), "load");
        assert_eq!(qualified("net", "sendTextWithTimeout"), "writeTimeout");
        assert_eq!(
            qualified("http", "sendTextResponseWithHeaders"),
            "respondHeaders"
        );
        assert_eq!(qualified("time", "utcDayOfYear"), "dayOfYear");
        assert_eq!(
            qualified_impl("android", "record"),
            "startMicrophoneRecording"
        );
        assert_eq!(qualified_impl("net", "readManyFrom"), "receiveTextFromMany");
        assert_eq!(global("distinct"), "unique");
        assert_eq!(global("where"), "where");
        assert_eq!(global_impl("unique"), "distinct");
        assert_eq!(global("concat"), "merge");
        assert_eq!(global_impl("merge"), "concat");
        assert_eq!(list_member("isNotEmpty"), "nonempty");
        assert_eq!(list_member_impl("only"), "single");
    }
}
